# Data settings
PATH_BASE_DATA:           'data/'
PATH_LABELED_ANNOTATIONS: 'task2/train_data/annotations.csv'


COL_IMAGE_PATH:   'renamed_path'
COL_LABEL:        'label_idx'

SEED:           42

# DataLoaders configuration
SIZE:            128
BATCH_SIZE:      128
VALID_PCT:       0.2
NUM_WORKERS:     0
MIN_SCALE:       0.35
FLIP_ITEM:       0.5
RANDOM_ERASE_P:  0.5
MAX_COUNT:       3

# Learner configuration
ARCH:           'xresnet50' # Network architecture (ResNet50, xResNet50)
OPT:            'ranger'      # Optimizer (Adam, ranger)
ACT_FN:         'mish'
N_OUT:          100
SA:             1
SYM:            0
POOL:           'avg_pool'
MOM:            0.95
SQR_MOM:        0.99
EPS:            0.000001
BETA:           0
FP16:           True        # Mixed precision training